### ISSUE TITLE
getting `Use of undeclared identifier 'glm'` error.

### ISSUE THREAD

**Issue by JotaroS** [edap/ofxBranchesPrimitive#1]
![2017-08-19 14 52 10](https://user-images.githubusercontent.com/9479730/29486758-fea6480c-84ed-11e7-8ffb-16164f85136c.png)

Hi @edap , I tried your example of this then keep getting this error.
My environment is

```
of 0.9.8 osx
macOS sierra 10.12.6
XCode 8.3.3
```
Sorry for brevity. Thanks,

Joe

**Comment by edap** [comment]
Hey Joe!
It looks like you are using a version of openFrameworks that is not using `glm`. I do not know which one was the release the started to use `glm` by default, for sure the current version that you can download from the website has it. Let me know if this can fix the issue.

**Comment by JotaroS** [comment]
OK, let me try it out.

**Comment by JotaroS** [comment]
@edap 
Thanks, and ___it worked___ on nighty build on osx!!
Now closing issue :)

Joe
